apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: faulty-split
  namespace: squidgame
spec:
  service: grcp-app-macario
  backends:
  - service: grcp-app-macario
    weight: 400m
  - service: grcp-app-oscar
    weight: 400m
  - service: faulty-traffic
    weight: 200m
